import json
import os
from agno.tools import tool

STATE_FILE = "state/learning_state.json"


def load_state():
    """
    Load the learning state safely.
    """

    if not os.path.exists(STATE_FILE):
        return {
            "roadmap": [],
            "topic": "",
            "current_week": 1,
            "current_topic_index": 0,
            "completed_topics": []
        }

    with open(STATE_FILE, "r") as f:
        content = f.read().strip()

        if not content:
            return {
                "roadmap": [],
                "topic": "",
                "current_week": 1,
                "current_topic_index": 0,
                "completed_topics": []
            }

        return json.loads(content)


def save_state(state):
    """
    Save learning state to file.
    """

    os.makedirs("state", exist_ok=True)

    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=4)


@tool
def store_roadmap(roadmap: dict):
    """
    Store the roadmap generated by the planner agent.
    """

    state = load_state()

    state["roadmap"] = roadmap["roadmap"]
    state["topic"] = roadmap["topic"]
    state["current_week"] = 1
    state["current_topic_index"] = 0
    state["completed_topics"] = []

    save_state(state)

    return {"status": "roadmap stored successfully"}


@tool
def get_next_topic():
    """
    Fetch the next topic the learner should study.
    """

    state = load_state()

    roadmap = state["roadmap"]
    week = state["current_week"]
    topic_index = state["current_topic_index"]

    if not roadmap:
        return {"error": "Roadmap not found"}

    if week > len(roadmap):
        return {"message": "Learning roadmap completed 🎉"}

    topics = roadmap[week - 1]["topics"]

    if topic_index >= len(topics):
        return {"message": "All topics completed for this week"}

    topic = topics[topic_index]

    return {
        "week": week,
        "topic": topic
    }


@tool
def complete_topic():
    """
    Mark the current topic as completed and move to the next topic.
    """

    state = load_state()

    roadmap = state["roadmap"]
    week = state["current_week"]
    topic_index = state["current_topic_index"]

    if week > len(roadmap):
        return {"message": "All roadmap topics completed"}

    topics = roadmap[week - 1]["topics"]

    topic = topics[topic_index]

    state["completed_topics"].append(topic)
    state["current_topic_index"] += 1

    if state["current_topic_index"] >= len(topics):
        state["current_week"] += 1
        state["current_topic_index"] = 0

    save_state(state)

    return {
        "status": "topic completed",
        "topic": topic
    }